modLoader = "javafml"
loaderVersion = "${neo_loader_version_range}"

license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
displayName = "${mod_name}"
version = "${mod_version}"
authors = "${mod_authors}"
description = '''${mod_description}'''
logoFile = "assets/nothing/logo.png"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "CLIENT"
